/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * addtreatment.java
 *
 * Created on Dec 26, 2011, 2:54:18 PM
 */

package view;

import Controller.Controller;
import DB.DbConnection;
import Model.mTreatment;
import Utility.generatedId;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class addtreatment extends javax.swing.JFrame {
Connection con;
PreparedStatement pst;
Statement st;
ResultSet rs;
private String query;

/** Creates new form addtreatment */
    public addtreatment()throws ClassNotFoundException, SQLException {
      
        initComponents();
        

        lblcostval.setVisible(false);
                query = "SELECT T_id FROM tbl_Treatment";
            txttreatid.setText("T"+generatedId.generateID(query));

          
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpatid = new javax.swing.JTextField();
        txtpatname = new javax.swing.JTextField();
        lblnameval = new javax.swing.JLabel();
        rdopatid = new javax.swing.JRadioButton();
        cbopatid = new javax.swing.JComboBox();
        btnsearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txttreatid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbotreatname = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtcost = new javax.swing.JTextField();
        lblcostval = new javax.swing.JLabel();
        btnpsave1 = new javax.swing.JButton();
        btnpcancel1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnpatback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD TREATMENT");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 5, true), "PATIENT DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("PATIENT ID :");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("PATIENT NAME:");

        txtpatid.setEditable(false);

        txtpatname.setEditable(false);
        txtpatname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpatnameKeyTyped(evt);
            }
        });

        lblnameval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblnamevalKeyTyped(evt);
            }
        });

        rdopatid.setBackground(new java.awt.Color(153, 204, 255));
        rdopatid.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rdopatid.setForeground(new java.awt.Color(51, 51, 255));
        rdopatid.setText("PATIENT ID :");
        rdopatid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdopatidActionPerformed(evt);
            }
        });

        cbopatid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbopatid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbopatidItemStateChanged(evt);
            }
        });
        cbopatid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbopatidActionPerformed(evt);
            }
        });

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gSearch1.jpg"))); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(rdopatid)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnameval)
                            .addComponent(txtpatname, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addGap(125, 125, 125))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbopatid, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtpatid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addComponent(btnsearch)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsearch, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                    .addComponent(rdopatid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbopatid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(txtpatid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtpatname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblnameval)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 5, true), "TREATMENT DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("TREATMENT ID :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("TREATMENT NAME :");

        cbotreatname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Root canal", "Filling", "Porcelain lamination", "Whitening", "Bleaching", "Bridge prosthesis", "Claening", "Tooth implant", "Fixing braces" }));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("COST :");

        txtcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcostKeyTyped(evt);
            }
        });

        lblcostval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblcostvalKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(56, 56, 56)
                        .addComponent(txttreatid, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcost, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(lblcostval)
                            .addComponent(cbotreatname, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttreatid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(cbotreatname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblcostval)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnpsave1.setBackground(new java.awt.Color(153, 204, 255));
        btnpsave1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnpsave1.setForeground(new java.awt.Color(51, 51, 255));
        btnpsave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/treat.JPG"))); // NOI18N
        btnpsave1.setText("SAVE");
        btnpsave1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnpsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpsave1ActionPerformed(evt);
            }
        });

        btnpcancel1.setBackground(new java.awt.Color(153, 204, 255));
        btnpcancel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnpcancel1.setForeground(new java.awt.Color(51, 51, 255));
        btnpcancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gCancel1.jpg"))); // NOI18N
        btnpcancel1.setText("CANCEL");
        btnpcancel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnpcancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpcancel1ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/treatmnt.JPG"))); // NOI18N
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 5, true));

        btnpatback.setBackground(new java.awt.Color(153, 204, 255));
        btnpatback.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnpatback.setForeground(new java.awt.Color(51, 51, 255));
        btnpatback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.gif"))); // NOI18N
        btnpatback.setText("BACK");
        btnpatback.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnpatback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnpsave1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(btnpcancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(btnpatback, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpsave1)
                    .addComponent(btnpatback, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpcancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblnamevalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblnamevalKeyTyped
       

    }//GEN-LAST:event_lblnamevalKeyTyped

    private void lblcostvalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblcostvalKeyTyped
        
    }//GEN-LAST:event_lblcostvalKeyTyped

    private void btnpcancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpcancel1ActionPerformed
        
}//GEN-LAST:event_btnpcancel1ActionPerformed

    private void btnpatbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatbackActionPerformed


        homepage hp=new homepage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpatbackActionPerformed

    private void txtpatnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpatnameKeyTyped
         try
        {
            char ch =evt.getKeyChar();
            if(ch>='0' & ch<='9')
            {
                evt.consume();
                txtpatname.setText("");
                lblnameval.setVisible(true);
                lblnameval.setText("Enter Alphabets Only");
            }
            else
            {
                lblnameval.setVisible(false);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtpatnameKeyTyped

    private void txtcostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcostKeyTyped
         try
        {
            char ch =evt.getKeyChar();
            if(!(Character.isDigit(ch)))
            {
                evt.consume();
                txtcost.setText("");
                lblcostval.setVisible(true);
                lblcostval.setText("Enter Digits Only");
            }
            else
            {
                lblcostval.setVisible(false);
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtcostKeyTyped

     private void clearFields()
    {
      txtpatid.setText("");
      txtpatname.setText("");
      txttreatid.setText("");
      cbotreatname.setSelectedItem("");
      txtcost.setText("");

      lblcostval.setVisible(false);
    }

    private void btnpsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpsave1ActionPerformed
     if (txttreatid.getText().isEmpty() || txtcost.getText().isEmpty() || cbotreatname.getSelectedItem().equals(""))
           {
           JOptionPane.showMessageDialog(this,"Pls,Enter All Required Inputs","ErrorDialog",JOptionPane.ERROR_MESSAGE);

       }
 else
       {
        try {

            String Name = cbotreatname.getSelectedItem().toString();
            int Cost = Integer.parseInt(txtcost.getText());
            mTreatment mt = new mTreatment(txtpatid.getText(),txtpatname.getText(),txttreatid.getText(),Name,Cost );
            Controller.Addtodatabase(mt, "addTreatment");
            clearFields();

            //javax.swing.JOptionPane.showMessageDialog(this,"Your Details Have Been Added Succesfully");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(addtreatment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(addtreatment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnpsave1ActionPerformed
    }
    private void rdopatidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdopatidActionPerformed
     try {
            //btng.clearSelection();
            //            rdoPatid.setVisible(false);
            //            cboRdoid.setVisible(false);
           
            Connection con = DbConnection.getConnection();
            Statement stmt = (Statement) con.createStatement();
             st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs=st.executeQuery("select Pat_id from tbl_PatientDetails ");
            while (rs.next()) {
            cbopatid.addItem(rs.getString(1));

            }

        }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(addtreatment.class.getName()).log(Level.SEVERE, null, ex);
        }        catch (SQLException ex) {
            Logger.getLogger(addtreatment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_rdopatidActionPerformed

    private void cbopatidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbopatidActionPerformed
     if(cbopatid.getSelectedItem()==null) {

            btnsearch.disable();
        }
        
    }//GEN-LAST:event_cbopatidActionPerformed

    private void cbopatidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbopatidItemStateChanged
           
          

    }//GEN-LAST:event_cbopatidItemStateChanged

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        try
    {
             Connection con = DbConnection.getConnection();
            Statement stmt = (Statement) con.createStatement();
        String cbo=cbopatid.getSelectedItem().toString();
        st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            rs=st.executeQuery("select Pat_id,Pat_name from tbl_PatientDetails where Pat_id='"+cbo+"' ");
            while (rs.next()) {
                txtpatid.setText(rs.getString("Pat_id"));
                txtpatname.setText(rs.getString("Pat_name"));
             }

    }
        catch (ClassNotFoundException ex) {
            Logger.getLogger(addtreatment.class.getName()).log(Level.SEVERE, null, ex);
        }     catch (SQLException ex) {
            Logger.getLogger(addtreatment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsearchActionPerformed
       
    
    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpatback;
    private javax.swing.JButton btnpcancel1;
    private javax.swing.JButton btnpsave1;
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox cbopatid;
    private javax.swing.JComboBox cbotreatname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblcostval;
    private javax.swing.JLabel lblnameval;
    private javax.swing.JRadioButton rdopatid;
    private javax.swing.JTextField txtcost;
    private javax.swing.JTextField txtpatid;
    private javax.swing.JTextField txtpatname;
    private javax.swing.JTextField txttreatid;
    // End of variables declaration//GEN-END:variables

}
