/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * getpatient.java
 *
 * Created on Jan 8, 2012, 1:35:30 PM
 */

package view;

import DB.DbConnection;
import Model.mPatient;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author abc
 */
public class getpatient extends javax.swing.JFrame {

    /** Creates new form getpatient */
    public getpatient() {
        initComponents();
        mPatient o1= new mPatient(cbopatname,rdopatname);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnpupdate = new javax.swing.JButton();
        btnpatback2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rdopatname = new javax.swing.JRadioButton();
        cbopatname = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GET PATIENT");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));

        btnpupdate.setBackground(new java.awt.Color(153, 204, 255));
        btnpupdate.setFont(new java.awt.Font("Arial", 1, 24));
        btnpupdate.setForeground(new java.awt.Color(51, 51, 255));
        btnpupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UpdateIcon.png"))); // NOI18N
        btnpupdate.setText("UPDATE");
        btnpupdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnpupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpupdateActionPerformed(evt);
            }
        });

        btnpatback2.setBackground(new java.awt.Color(153, 204, 255));
        btnpatback2.setFont(new java.awt.Font("Arial", 1, 24));
        btnpatback2.setForeground(new java.awt.Color(51, 51, 255));
        btnpatback2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.gif"))); // NOI18N
        btnpatback2.setText("BACK");
        btnpatback2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnpatback2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatback2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        rdopatname.setBackground(new java.awt.Color(153, 204, 255));
        rdopatname.setFont(new java.awt.Font("Arial", 1, 18));
        rdopatname.setForeground(new java.awt.Color(51, 51, 255));
        rdopatname.setText("PATIENT NAME :");
        rdopatname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdopatnameActionPerformed(evt);
            }
        });

        cbopatname.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbopatname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbopatnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(rdopatname)
                .addGap(48, 48, 48)
                .addComponent(cbopatname, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdopatname)
                    .addComponent(cbopatname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnpupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnpatback2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpatback2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(1066, 1066, 1066))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdopatnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdopatnameActionPerformed
 try {
            //btng.clearSelection();
            //            rdoPatid.setVisible(false);
            //            cboRdoid.setVisible(false);
            cbopatname.removeAllItems();
            Connection con = DbConnection.getConnection();
            Statement stmt = (Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery("select Pat_name from tbl_PatientDetails");
            while (rs.next()) {
                cbopatname.addItem(rs.getString(1));

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(updatepatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(updatepatient.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_rdopatnameActionPerformed

    private void cbopatnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbopatnameActionPerformed
        if(cbopatname.getSelectedItem()==null) {

            btnpupdate.disable();
        }
}//GEN-LAST:event_cbopatnameActionPerformed

    private void btnpupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpupdateActionPerformed
        int cnt1=cbopatname.getItemCount();
        int i1=cbopatname.getSelectedIndex();
        if( cnt1==0) {
            JOptionPane.showMessageDialog(null,"There is no patient to fill Patient details");
        } else if( i1==-1) {
            JOptionPane.showMessageDialog(null,"Please Select patient to insert its  details!!!");
        } else{
            try {
                updatepatient mp = new updatepatient();
                mp.setVisible(true);
                this.dispose();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(getpatient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(getpatient.class.getName()).log(Level.SEVERE, null, ex);
            }
            

}//GEN-LAST:event_btnpupdateActionPerformed
    }
        private void btnpatback2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatback2ActionPerformed

            homepage hp=new homepage();
            hp.setVisible(true);
            this.dispose();
}//GEN-LAST:event_btnpatback2ActionPerformed
    
    /**
    * @param args the command line arguments
    */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpatback2;
    private javax.swing.JButton btnpupdate;
    public static javax.swing.JComboBox cbopatname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JRadioButton rdopatname;
    // End of variables declaration//GEN-END:variables

}
