/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * progress.java
 *
 * Created on Nov 12, 2011, 11:18:11 AM
 */

package view;



/**
 *
 * @author abc
 */
public class start extends javax.swing.JFrame {
    int i=0;
    /** Creates new form progress */
    public start() {
        initComponents();
        Timerschedule t=new Timerschedule();
        java.util.Timer time=new java.util.Timer();
        time.schedule(t,100,100);
    }
    class Timerschedule extends java.util.TimerTask
    {
        public void run()
        {
            
            jProgressBar.setValue(i);
            i++;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPLASH PAGE");
        setBackground(new java.awt.Color(153, 204, 255));

        jProgressBar.setStringPainted(true);
        jProgressBar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jProgressBarStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(481, Short.MAX_VALUE)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(408, 408, 408))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProgressBarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBarStateChanged
        if(jProgressBar.getValue()==jProgressBar.getMaximum())
        {
            login log=new login();
            log.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jProgressBarStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables

}
