/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * updatepatient.java
 *
 * Created on Nov 22, 2011, 6:30:43 PM
 */

package view;

import Controller.Controller;
import DB.DbConnection;
import Model.mPatient;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author abc
 */
public class updatepatient extends javax.swing.JFrame {

    /** Creates new form updatepatient */
    public updatepatient() throws ClassNotFoundException, SQLException {
        initComponents();
        lblpageval.setVisible(false);
        lblpcontactval.setVisible(false);
         
        getpatient.rdopatname.setText("Pat_name");
            String rdo=getpatient.rdopatname.getText();
            String cbo=getpatient.cbopatname.getSelectedItem().toString();
            Connection con = DbConnection.getConnection();
            Statement stmt = (Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery("select Pat_id,Pat_name,Address,Age,Contact,Complaint,Medical_history,Medication,History_allergy,Softtissue,Hardtissue from tbl_PatientDetails where "+rdo+" = '"+cbo+"'");
            while(rs.next())
            {
                    String patid=rs.getString("Pat_id");
                    txtpid.setText(""+patid);
                    String patname=rs.getString("Pat_name");
                    txtpname.setText(""+patname);
                    String Address = rs.getString("Address");
                    txtadd.setText("" + Address);
                    String cnt=rs.getString("Contact");
                    txtcontact.setText(""+cnt);
                    String Age=rs.getString("Age");
                    txtage.setText(""+Age);

                    String comp=rs.getString("Complaint");
                    txtacomp.setText(""+comp);
                    String hist=rs.getString("Medical_history");
                    txtahistory.setText(""+hist);
                    String med=rs.getString("Medication");
                    txtamedi.setText(""+med);
                    String alle=rs.getString("History_allergy");
                    txtaallergy.setText(""+alle);
                    String soft=rs.getString("Softtissue");
                    cbosoft.setSelectedItem(""+soft);
                    String hard=rs.getString("Hardtissue");
                    cbohard.setSelectedItem(""+hard);
            }
            con.close();
    
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlpatient1 = new javax.swing.JPanel();
        btnpupdate = new javax.swing.JButton();
        btnpcancel = new javax.swing.JButton();
        btnpatback = new javax.swing.JButton();
        lblpname1 = new javax.swing.JLabel();
        txtpname = new javax.swing.JTextField();
        pnlupdate = new javax.swing.JPanel();
        pnlpersonal = new javax.swing.JPanel();
        lblpage1 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        lbladd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();
        lblcontact = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        lblpcontactval = new javax.swing.JLabel();
        lblpageval = new javax.swing.JLabel();
        lblcontactval = new javax.swing.JLabel();
        pnlmedhistory = new javax.swing.JPanel();
        lblcom = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtacomp = new javax.swing.JTextArea();
        lblmed = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtahistory = new javax.swing.JTextArea();
        lblmedi = new javax.swing.JLabel();
        lblhist = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtamedi = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtaallergy = new javax.swing.JTextArea();
        lblsoft = new javax.swing.JLabel();
        lblhard = new javax.swing.JLabel();
        cbosoft = new javax.swing.JComboBox();
        cbohard = new javax.swing.JComboBox();
        lblnameval = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtpid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UPDATE PATIENT");

        pnlpatient1.setBackground(new java.awt.Color(51, 153, 255));
        pnlpatient1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));

        btnpupdate.setBackground(new java.awt.Color(153, 204, 255));
        btnpupdate.setFont(new java.awt.Font("Arial", 1, 24));
        btnpupdate.setForeground(new java.awt.Color(51, 51, 255));
        btnpupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UpdateIcon.png"))); // NOI18N
        btnpupdate.setText("UPDATE");
        btnpupdate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnpupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpupdateActionPerformed(evt);
            }
        });

        btnpcancel.setBackground(new java.awt.Color(153, 204, 255));
        btnpcancel.setFont(new java.awt.Font("Arial", 1, 24));
        btnpcancel.setForeground(new java.awt.Color(51, 51, 255));
        btnpcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CancelPat.JPG"))); // NOI18N
        btnpcancel.setText("CANCEL");
        btnpcancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnpcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpcancelActionPerformed(evt);
            }
        });

        btnpatback.setBackground(new java.awt.Color(153, 204, 255));
        btnpatback.setFont(new java.awt.Font("Arial", 1, 24));
        btnpatback.setForeground(new java.awt.Color(51, 51, 255));
        btnpatback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.gif"))); // NOI18N
        btnpatback.setText("BACK");
        btnpatback.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnpatback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatbackActionPerformed(evt);
            }
        });

        lblpname1.setFont(new java.awt.Font("Arial", 1, 18));
        lblpname1.setForeground(new java.awt.Color(51, 51, 255));
        lblpname1.setText("NAME :");

        txtpname.setEditable(false);
        txtpname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpnameKeyTyped(evt);
            }
        });

        pnlupdate.setBackground(new java.awt.Color(153, 204, 255));
        pnlupdate.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 5, true), "UPDATE PATIENT DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        pnlpersonal.setBackground(new java.awt.Color(153, 204, 255));
        pnlpersonal.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 5, true), "PERSONAL DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        lblpage1.setFont(new java.awt.Font("Arial", 1, 18));
        lblpage1.setForeground(new java.awt.Color(51, 51, 255));
        lblpage1.setText("AGE :");

        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtageKeyTyped(evt);
            }
        });

        lbladd.setFont(new java.awt.Font("Arial", 1, 18));
        lbladd.setForeground(new java.awt.Color(51, 51, 255));
        lbladd.setText("ADDRESS :");

        txtadd.setColumns(20);
        txtadd.setRows(5);
        jScrollPane1.setViewportView(txtadd);

        lblcontact.setFont(new java.awt.Font("Arial", 1, 18));
        lblcontact.setForeground(new java.awt.Color(51, 51, 255));
        lblcontact.setText("CONTACT NO. :");

        txtcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcontactKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlpersonalLayout = new javax.swing.GroupLayout(pnlpersonal);
        pnlpersonal.setLayout(pnlpersonalLayout);
        pnlpersonalLayout.setHorizontalGroup(
            pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpersonalLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcontact)
                    .addComponent(lbladd)
                    .addComponent(lblpage1))
                .addGap(18, 18, 18)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblpcontactval)
                    .addComponent(lblcontactval)
                    .addComponent(lblpageval)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlpersonalLayout.setVerticalGroup(
            pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpersonalLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpage1)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblpageval)
                .addGap(35, 35, 35)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpersonalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbladd))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(pnlpersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontact)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblpcontactval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lblcontactval)
                .addGap(27, 27, 27))
        );

        pnlmedhistory.setBackground(new java.awt.Color(153, 204, 255));
        pnlmedhistory.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 5, true), "MEDICAL-HISTORY DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        lblcom.setFont(new java.awt.Font("Arial", 1, 18));
        lblcom.setForeground(new java.awt.Color(51, 51, 255));
        lblcom.setText("CHIEF-COMPLAINT :");

        txtacomp.setColumns(20);
        txtacomp.setRows(5);
        jScrollPane2.setViewportView(txtacomp);

        lblmed.setFont(new java.awt.Font("Arial", 1, 18));
        lblmed.setForeground(new java.awt.Color(51, 51, 255));
        lblmed.setText("PAST MEDICAL HISTORY :");

        txtahistory.setColumns(20);
        txtahistory.setRows(5);
        jScrollPane3.setViewportView(txtahistory);

        lblmedi.setFont(new java.awt.Font("Arial", 1, 18));
        lblmedi.setForeground(new java.awt.Color(51, 51, 255));
        lblmedi.setText("MEDICATION :");

        lblhist.setFont(new java.awt.Font("Arial", 1, 18));
        lblhist.setForeground(new java.awt.Color(51, 51, 255));
        lblhist.setText("HISTORY OF ALLERGY :");

        txtamedi.setColumns(20);
        txtamedi.setRows(5);
        jScrollPane4.setViewportView(txtamedi);

        txtaallergy.setColumns(20);
        txtaallergy.setRows(5);
        jScrollPane5.setViewportView(txtaallergy);

        lblsoft.setFont(new java.awt.Font("Arial", 1, 18));
        lblsoft.setForeground(new java.awt.Color(51, 51, 255));
        lblsoft.setText("SOFT TISSUE :");

        lblhard.setFont(new java.awt.Font("Arial", 1, 18));
        lblhard.setForeground(new java.awt.Color(51, 51, 255));
        lblhard.setText("HARD TISSUE :");

        cbosoft.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gums", "Lips", "Tongue", " " }));

        cbohard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Teeth", "Jaws", " " }));

        javax.swing.GroupLayout pnlmedhistoryLayout = new javax.swing.GroupLayout(pnlmedhistory);
        pnlmedhistory.setLayout(pnlmedhistoryLayout);
        pnlmedhistoryLayout.setHorizontalGroup(
            pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcom)
                    .addComponent(lblmed)
                    .addComponent(lblsoft)
                    .addComponent(lblhard)
                    .addComponent(lblmedi)
                    .addComponent(lblhist))
                .addGroup(pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmedhistoryLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlmedhistoryLayout.createSequentialGroup()
                                .addComponent(cbohard, 0, 173, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                                .addGroup(pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbosoft, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                                .addContainerGap())))))
        );
        pnlmedhistoryLayout.setVerticalGroup(
            pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                .addGroup(pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblcom))
                    .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblmed))
                    .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblmedi))
                    .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlmedhistoryLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblhist)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsoft)
                    .addComponent(cbosoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnlmedhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhard)
                    .addComponent(cbohard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout pnlupdateLayout = new javax.swing.GroupLayout(pnlupdate);
        pnlupdate.setLayout(pnlupdateLayout);
        pnlupdateLayout.setHorizontalGroup(
            pnlupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlupdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlpersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlmedhistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlupdateLayout.setVerticalGroup(
            pnlupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlupdateLayout.createSequentialGroup()
                .addGroup(pnlupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlupdateLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(pnlpersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlmedhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("PATIENT ID :");

        txtpid.setEditable(false);

        javax.swing.GroupLayout pnlpatient1Layout = new javax.swing.GroupLayout(pnlpatient1);
        pnlpatient1.setLayout(pnlpatient1Layout);
        pnlpatient1Layout.setHorizontalGroup(
            pnlpatient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpatient1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(lblpname1)
                .addGap(28, 28, 28)
                .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblnameval)
                .addGap(555, 555, 555))
            .addGroup(pnlpatient1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnpupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(btnpcancel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(btnpatback, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(585, Short.MAX_VALUE))
            .addGroup(pnlpatient1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        pnlpatient1Layout.setVerticalGroup(
            pnlpatient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpatient1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlpatient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpname1)
                    .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnameval)
                    .addComponent(jLabel1)
                    .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(pnlupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlpatient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpcancel)
                    .addComponent(btnpatback))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlpatient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlpatient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpnameKeyTyped
        try {
            char ch =evt.getKeyChar();
            if(ch>='0' & ch<='9') {
                evt.consume();
                txtpname.setText("");
                lblnameval.setVisible(true);
                lblnameval.setText("Enter Alphabets Only");
            } else {
                lblnameval.setVisible(false);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_txtpnameKeyTyped

    private void btnpatbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatbackActionPerformed
        
        homepage hp=new homepage();
        hp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpatbackActionPerformed

    private void txtageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyTyped
        try {
            char ch =evt.getKeyChar();
            if(!(Character.isDigit(ch))) {
                evt.consume();
                txtage.setText("");
                lblpageval.setVisible(true);
                lblpageval.setText("Enter Digits Only");
            } else {
                lblpageval.setVisible(false);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_txtageKeyTyped

    private void txtcontactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactKeyTyped
        try {
            char ch =evt.getKeyChar();
            if(!(Character.isDigit(ch))) {
                evt.consume();
                txtcontact.setText("");
                lblpcontactval.setVisible(true);
                lblpcontactval.setText("Enter Digits Only");
            } else {
                lblpcontactval.setVisible(false);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
         char c=evt.getKeyChar();
        if(!((Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE))) {
            getToolkit().beep();
            evt.consume();
            lblpcontactval.setVisible(true);
        } else{
            lblpcontactval.setVisible(false);
        }
}//GEN-LAST:event_txtcontactKeyTyped

    private void btnpcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpcancelActionPerformed
        clear();
    }//GEN-LAST:event_btnpcancelActionPerformed

    private void btnpupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpupdateActionPerformed
    if (txtage.getText().isEmpty() || txtadd.getText().isEmpty() || txtcontact.getText().isEmpty() ||txtacomp.getText().isEmpty() || txtamedi.getText().isEmpty() || txtamedi.getText().isEmpty() || txtahistory.getText().isEmpty()  || cbosoft.getSelectedItem().equals("") || cbohard.getSelectedItem().equals(""))
           {
           JOptionPane.showMessageDialog(this,"Pls,Enter All Required Inputs","ErrorDialog",JOptionPane.ERROR_MESSAGE);

       }
 else
       {
        try {
                String Soft = cbosoft.getSelectedItem().toString();
                String Hard = cbohard.getSelectedItem().toString();
                mPatient mpt = new mPatient(txtpid.getText(),txtpname.getText(),txtadd.getText(),Integer.parseInt(txtage.getText()), txtcontact.getText(), txtacomp.getText(),txtahistory.getText(),txtamedi.getText(),txtaallergy.getText(),Soft,Hard);
                Controller.UpdateINdatabase(mpt, "updatePatientDetails");
                clear();
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(addpatient.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(addpatient.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnpupdateActionPerformed
public void clear()
        {
    txtage.setText("");
    txtadd.setText("");
    txtcontact.setText("");
    txtamedi.setText("");
    txtaallergy.setText("");
    txtacomp.setText("");
    txtahistory.setText("");

}
    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpatback;
    private javax.swing.JButton btnpcancel;
    private javax.swing.JButton btnpupdate;
    private javax.swing.JComboBox cbohard;
    private javax.swing.JComboBox cbosoft;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbladd;
    private javax.swing.JLabel lblcom;
    private javax.swing.JLabel lblcontact;
    private javax.swing.JLabel lblcontactval;
    private javax.swing.JLabel lblhard;
    private javax.swing.JLabel lblhist;
    private javax.swing.JLabel lblmed;
    private javax.swing.JLabel lblmedi;
    private javax.swing.JLabel lblnameval;
    private javax.swing.JLabel lblpage1;
    private javax.swing.JLabel lblpageval;
    private javax.swing.JLabel lblpcontactval;
    private javax.swing.JLabel lblpname1;
    private javax.swing.JLabel lblsoft;
    private javax.swing.JPanel pnlmedhistory;
    private javax.swing.JPanel pnlpatient1;
    private javax.swing.JPanel pnlpersonal;
    private javax.swing.JPanel pnlupdate;
    private javax.swing.JTextArea txtaallergy;
    private javax.swing.JTextArea txtacomp;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextArea txtahistory;
    private javax.swing.JTextArea txtamedi;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpname;
    // End of variables declaration//GEN-END:variables

}
