/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * updatepayment.java
 *
 * Created on Dec 28, 2011, 2:49:57 PM
 */

package view;

import Controller.Controller;
import DB.DbConnection;
import Model.mPayment;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author abc
 */
public class updatepayment extends javax.swing.JFrame {

    /** Creates new form updatepayment */
    public updatepayment() {
        try {
            initComponents();
            
            getpayment.rdopatname.setText("Pat_name");
            String rdo = getpayment.rdopatname.getText();
            String cbo = getpayment.cbopatname.getSelectedItem().toString();
            Connection conn = DbConnection.getConnection();
            Statement stmt1 = (Statement) conn.createStatement();
            ResultSet rs1=stmt1.executeQuery("select T_name,T_cost from tbl_Treatment where " + rdo + " = '" + cbo + "'");
            while (rs1.next()) {
//                String tid = rs1.getString("t_id");
//                txtTreat_id.setText("" + tid);
                String tname = rs1.getString("T_name");
                txttreatname.setText("" + tname);
                String tamt = rs1.getString("T_cost");
                txttotcharge.setText("" + tamt);
            }
            conn.close();
            Connection con = DbConnection.getConnection();
            Statement stmt = (Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery("select Pat_id,Pat_name,Paid_amt from tbl_Payment where " + rdo + " = '" + cbo + "'");
            while (rs.next()) {
                String patid = rs.getString("Pat_id");
                txtpatid.setText("" + patid);
                String patname = rs.getString("Pat_name");
                txtpatname.setText("" + patname);
                
//                String pamt = rs.getString("paid_amt");
//                txtP_amt.setText("" + pamt);
                String peamt = rs.getString("Paid_amt");
                txttotpaid.setText("" + peamt);

            }
            con.close();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(updatepayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(updatepayment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

     public int Amt()
     {
         int tamt= Integer.parseInt(txttotpaid.getText());
         int pamt=Integer.parseInt(txtpaid.getText());
         int toamt=Integer.parseInt(txttotcharge.getText());
         int cal=toamt-tamt;
         int bal=cal-pamt;
         return bal;

     }
     public int Amt1()
     {
         int tamt= Integer.parseInt(txttotpaid.getText());
         int pamt=Integer.parseInt(txtpaid.getText());
         int bal=tamt+pamt;
         return bal;

     }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtpaid = new javax.swing.JTextField();
        lblpaidval = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        lblbalval = new javax.swing.JLabel();
        btnpsave1 = new javax.swing.JButton();
        btnpcancel1 = new javax.swing.JButton();
        btnpatback = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpatid = new javax.swing.JTextField();
        txtpatname = new javax.swing.JTextField();
        lblnameval = new javax.swing.JLabel();
        txttreatname = new javax.swing.JTextField();
        txttotcharge = new javax.swing.JTextField();
        txttotpaid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UPDATE PAYMENT");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 5));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 5, true), "UPDATE PAYMENT DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("AMOUNT PAID :");

        txtpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaidActionPerformed(evt);
            }
        });
        txtpaid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpaidFocusLost(evt);
            }
        });
        txtpaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpaidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpaidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpaidKeyTyped(evt);
            }
        });

        lblpaidval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblpaidvalKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("BALANCE AMOUNT :");

        txtbalance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbalanceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbalanceKeyTyped(evt);
            }
        });

        lblbalval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblbalvalKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblpaidval)
                                .addContainerGap())
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtpaid, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addGap(27, 27, 27))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblbalval)
                                .addContainerGap())
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtbalance, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addGap(25, 25, 25))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtpaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblpaidval)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblbalval)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnpsave1.setBackground(new java.awt.Color(153, 204, 255));
        btnpsave1.setFont(new java.awt.Font("Arial", 1, 24));
        btnpsave1.setForeground(new java.awt.Color(51, 51, 255));
        btnpsave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.jpg"))); // NOI18N
        btnpsave1.setText("UPDATE");
        btnpsave1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnpsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpsave1ActionPerformed(evt);
            }
        });

        btnpcancel1.setBackground(new java.awt.Color(153, 204, 255));
        btnpcancel1.setFont(new java.awt.Font("Arial", 1, 24));
        btnpcancel1.setForeground(new java.awt.Color(51, 51, 255));
        btnpcancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gCancel1.jpg"))); // NOI18N
        btnpcancel1.setText("CANCEL");
        btnpcancel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnpcancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpcancel1ActionPerformed(evt);
            }
        });

        btnpatback.setBackground(new java.awt.Color(153, 204, 255));
        btnpatback.setFont(new java.awt.Font("Arial", 1, 24));
        btnpatback.setForeground(new java.awt.Color(51, 51, 255));
        btnpatback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.gif"))); // NOI18N
        btnpatback.setText("BACK");
        btnpatback.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 2, true));
        btnpatback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatbackActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pay.jpg"))); // NOI18N
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 5, true));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 5, true));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("PATIENT ID :");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("PATIENT NAME:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("TREATMENT NAME :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("TOTAL CHARGE :");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("TOTAL PAID AMOUNT :");

        txtpatid.setEditable(false);

        txtpatname.setEditable(false);
        txtpatname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpatnameKeyTyped(evt);
            }
        });

        lblnameval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblnamevalKeyTyped(evt);
            }
        });

        txttreatname.setEditable(false);

        txttotcharge.setEditable(false);

        txttotpaid.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblnameval)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttotcharge)
                            .addComponent(txttotpaid, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txttreatname)
                            .addComponent(txtpatname, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtpatid, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpatid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtpatname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(lblnameval)
                        .addGap(18, 18, 18)
                        .addComponent(txttreatname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txttotcharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txttotpaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnpsave1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(btnpcancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(btnpatback, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpsave1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpcancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpatback, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblnamevalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblnamevalKeyTyped
        
}//GEN-LAST:event_lblnamevalKeyTyped

    private void txtpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaidActionPerformed

}//GEN-LAST:event_txtpaidActionPerformed

    private void txtpaidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaidKeyTyped
        try {
            char ch =evt.getKeyChar();
            if(!(Character.isDigit(ch))) {
                evt.consume();
                txtpaid.setText("");
                lblpaidval.setVisible(true);
                lblpaidval.setText("Enter Digits Only");
            } else {
                lblpaidval.setVisible(false);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_txtpaidKeyTyped

    private void lblpaidvalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblpaidvalKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_lblpaidvalKeyTyped

    private void txtbalanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbalanceKeyTyped
        try {
            char ch =evt.getKeyChar();
            if(!(Character.isDigit(ch))) {
                evt.consume();
                txtbalance.setText("");
                lblbalval.setVisible(true);
                lblbalval.setText("Enter Digits Only");
            } else {
                lblbalval.setVisible(false);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_txtbalanceKeyTyped

    private void lblbalvalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblbalvalKeyTyped
        // TODO add your handling code here:
}//GEN-LAST:event_lblbalvalKeyTyped

    private void btnpcancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpcancel1ActionPerformed

}//GEN-LAST:event_btnpcancel1ActionPerformed

    private void btnpatbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatbackActionPerformed


        homepage hp=new homepage();
        hp.setVisible(true);
        this.dispose();
}//GEN-LAST:event_btnpatbackActionPerformed

    private void txtpatnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpatnameKeyTyped
        try {
            char ch =evt.getKeyChar();
            if(ch>='0' & ch<='9') {
                evt.consume();
                txtpatname.setText("");
                lblnameval.setVisible(true);
                lblnameval.setText("Enter Alphabets Only");
            } else {
                lblnameval.setVisible(false);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtpatnameKeyTyped

    private void btnpsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpsave1ActionPerformed
        if (txtpaid.getText().isEmpty() || txtbalance.getText().isEmpty())
           {
           JOptionPane.showMessageDialog(this,"Pls,Enter All Required Inputs","ErrorDialog",JOptionPane.ERROR_MESSAGE);

       }
 else
       {
        try {
            mPayment mt = new mPayment(txtpatid.getText(), txtpatname.getText(), Integer.parseInt(txttotpaid.getText()), Integer.parseInt(txtbalance.getText()));
            Controller.UpdateINdatabase(mt, "updatePayment");
            clear();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(updatepayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(updatepayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnpsave1ActionPerformed
    }
    private void txtpaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaidKeyReleased
         txtbalance.setText(Integer.toString(Amt()));
          
    }//GEN-LAST:event_txtpaidKeyReleased

    private void txtbalanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbalanceKeyReleased
       
    }//GEN-LAST:event_txtbalanceKeyReleased

    private void txtpaidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaidKeyPressed
      
    }//GEN-LAST:event_txtpaidKeyPressed

    private void txtpaidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpaidFocusLost
         txttotpaid.setText(Integer.toString(Amt1()));
    }//GEN-LAST:event_txtpaidFocusLost
public void clear()
{
    txtpaid.setText("");
    txttotpaid.setText("");
    txtpatid.setText("");
    txtpatname.setText("");
    txttreatname.setText("");
    txttotcharge.setText("");
    txtbalance.setText("");
}
    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpatback;
    private javax.swing.JButton btnpcancel1;
    private javax.swing.JButton btnpsave1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblbalval;
    private javax.swing.JLabel lblnameval;
    private javax.swing.JLabel lblpaidval;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtpaid;
    private javax.swing.JTextField txtpatid;
    private javax.swing.JTextField txtpatname;
    private javax.swing.JTextField txttotcharge;
    private javax.swing.JTextField txttotpaid;
    private javax.swing.JTextField txttreatname;
    // End of variables declaration//GEN-END:variables

}
